import os
import json
import hashlib
import random
import string


class EcologyEngine:
    """
    A minimal, self-contained ecology engine that scans test files,
    generates pressure (new test files with random mutation patterns),
    and evolves tests by adding new test cases for untested scenarios.
    Uses only standard library imports.
    """

    def __init__(self):
        self.test_files = []
        self.mutation_patterns = [
            "new_assertion_type",
            "new_edge_case",
            "new_boundary_condition",
            "new_exception_handling",
            "new_parameter_combination"
        ]

    def scan_test_suite(self):
        """
        Lists all test_*.py files in the current directory.
        Returns a list of filenames.
        """
        self.test_files = []
        for filename in os.listdir('.'):
            if filename.startswith('test_') and filename.endswith('.py'):
                self.test_files.append(filename)
        return self.test_files

    def generate_pressure(self):
        """
        Creates a new test file with a random mutation pattern.
        The new file is named pressure_<random_hash>.py.
        Returns the filename of the created file.
        """
        # Generate a unique filename based on hash of random data
        random_data = ''.join(random.choices(string.ascii_letters + string.digits, k=16))
        file_hash = hashlib.sha256(random_data.encode()).hexdigest()[:8]
        filename = f"pressure_{file_hash}.py"

        # Choose a random mutation pattern
        pattern = random.choice(self.mutation_patterns)

        # Generate test content based on the pattern
        test_content = self._generate_test_content(pattern, filename)

        # Write the file
        with open(filename, 'w') as f:
            f.write(test_content)

        return filename

    def _generate_test_content(self, pattern, filename):
        """Generate test file content based on the mutation pattern."""
        test_name = f"test_{pattern}_{filename.replace('.py', '')}"

        content = f'''"""
Auto-generated pressure test: {pattern}
Generated by EcologyEngine
"""
import unittest


class {test_name}(unittest.TestCase):
    """Test class for {pattern} pattern."""

    def test_{pattern}_basic(self):
        """Basic test for {pattern} pattern."""
        # TODO: Implement actual test logic
        self.assertTrue(True)

    def test_{pattern}_edge(self):
        """Edge case test for {pattern} pattern."""
        # TODO: Implement edge case logic
        with self.assertRaises(Exception):
            raise NotImplementedError("Edge case not implemented")


if __name__ == '__main__':
    unittest.main()
'''
        return content

    def evolve_tests(self, test_file):
        """
        Modifies an existing test file to add a new test case that tests
        a currently untested scenario.
        
        Args:
            test_file (str): The filename of the test to evolve.
        
        Returns:
            bool: True if evolution was successful, False otherwise.
        """
        if test_file not in self.test_files:
            # Try to find the file directly
            if not os.path.exists(test_file):
                return False

        try:
            with open(test_file, 'r') as f:
                content = f.read()
        except FileNotFoundError:
            return False

        # Generate a new test method for an untested scenario
        new_test_method = self._generate_new_test_method(test_file)

        # Find the last test method in the file and insert before the class end
        # Simple approach: insert before the last line that starts with 'if __name__'
        # or before the end of the file
        lines = content.split('\n')
        insert_pos = len(lines)

        for i, line in enumerate(lines):
            if line.strip().startswith('if __name__'):
                insert_pos = i
                break

        # Insert the new test method
        lines.insert(insert_pos, new_test_method)
        new_content = '\n'.join(lines)

        # Write the modified content back
        with open(test_file, 'w') as f:
            f.write(new_content)

        return True

    def _generate_new_test_method(self, test_file):
        """Generate a new test method for an untested scenario."""
        # Create a unique test name based on the file
        base_name = test_file.replace('.py', '').replace('test_', '')
        test_name = f"test_{base_name}_untested_scenario_{random.randint(1000, 9999)}"

        method = f'''
    def {test_name}(self):
        """Test an untested scenario for {base_name}."""
        # TODO: Implement test for this untested scenario
        self.assertIsNotNone(None)
'''
        return method

    def get_test_files(self):
        """Return the list of currently tracked test files."""
        return self.test_files