"""Orchestrator module integrating feasibility estimation into goal execution flow."""

from typing import Any, Dict, List, Optional, Tuple
from dataclasses import dataclass, field
import logging

from goal_feasibility_estimator import GoalFeasibilityEstimator
from goal_generator import GoalGenerator

logger = logging.getLogger(__name__)

@dataclass
class Goal:
    """Represents a goal to be executed."""
    id: str
    description: str
    complexity: float = 1.0  # Default complexity
    sub_goals: List['Goal'] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

class Orchestrator:
    """Orchestrates goal execution with feasibility checking and goal generation."""

    def __init__(self, capabilities: List[str], history: List[Dict[str, Any]], goals_per_cycle: int = 3,
                 goal_generation_frequency: int = 5, max_concurrent_goals: int = 10):
        """
        Initialize the orchestrator.

        Args:
            capabilities: List of available capabilities
            history: Execution history for context
            goals_per_cycle: Number of goals to propose per reflection cycle
            goal_generation_frequency: Number of cycles between goal generation phases
            max_concurrent_goals: Maximum number of goals allowed in the execution queue
        """
        self.estimator = GoalFeasibilityEstimator()
        self.goal_generator = GoalGenerator()
        self.capabilities = capabilities
        self.history = history
        self.execution_queue: List[Goal] = []
        self.blocked_goals: List[Tuple[Goal, str]] = []  # (goal, reason)
        self.goals_per_cycle = goals_per_cycle
        self.goal_generation_frequency = goal_generation_frequency
        self.max_concurrent_goals = max_concurrent_goals
        self.cycle_count = 0
        self.generated_goals: List[Goal] = []  # Track generated goals to avoid duplicates

    def generate_and_prioritize_goals(self) -> Optional[Goal]:
        """
        Generate new goals using the goal generator and select the highest-priority goal for execution.

        Returns:
            Optional[Goal]: The highest-priority goal, or None if no goals were generated
        """
        # Build knowledge base from history
        knowledge_base = {
            "failure_logs": [],
            "success_patterns": [],
            "capabilities": self.capabilities,
            "blocked_goals": [(g.description, r) for g, r in self.blocked_goals]
        }
        
        # Extract failure logs and success patterns from history
        for entry in self.history:
            if entry.get("status") == "failed":
                knowledge_base["failure_logs"].append({
                    "goal_id": entry.get("goal_id"),
                    "description": entry.get("description", ""),
                    "reason": entry.get("reason", "Unknown failure")
                })
            elif entry.get("status") == "executed" or entry.get("status") == "completed":
                knowledge_base["success_patterns"].append({
                    "goal_id": entry.get("goal_id"),
                    "description": entry.get("description", ""),
                    "complexity": entry.get("complexity", 1.0)
                })

        # Generate new goals using the goal generator
        proposed_goals = self.goal_generator.generate_goals(
            knowledge_base=knowledge_base,
            num_goals=self.goals_per_cycle
        )

        if not proposed_goals:
            logger.info("No goals were generated by the goal generator")
            return None

        # Filter out duplicate goals (compare against existing capabilities and already generated goals)
        filtered_goals = []
        for goal in proposed_goals:
            # Check if goal description matches an existing capability
            is_duplicate = False
            for capability in self.capabilities:
                if capability.lower() in goal.description.lower() or goal.description.lower() in capability.lower():
                    is_duplicate = True
                    logger.info(f"Goal '{goal.id}' duplicates existing capability '{capability}', skipping")
                    break
            
            # Check if goal description matches already generated goals
            if not is_duplicate:
                for existing_goal in self.generated_goals:
                    if existing_goal.description.lower() == goal.description.lower():
                        is_duplicate = True
                        logger.info(f"Goal '{goal.id}' duplicates previously generated goal '{existing_goal.id}', skipping")
                        break
            
            if not is_duplicate:
                filtered_goals.append(goal)

        if not filtered_goals:
            logger.info("All proposed goals were duplicates, no new goals to add")
            return None

        # Evaluate feasibility for each proposed goal and select the highest-priority one
        best_goal = None
        best_priority = -1.0

        for goal in filtered_goals:
            # Estimate success probability
            probability = self.estimator.estimate_success_probability(
                goal, self.capabilities, self.history
            )
            
            # Calculate priority based on feasibility and complexity
            priority = probability * (1.0 / max(goal.complexity, 0.1))
            
            # Store feasibility information in metadata
            goal.metadata["feasibility_probability"] = probability
            goal.metadata["priority_score"] = priority
            
            if priority > best_priority:
                best_priority = priority
                best_goal = goal

        if best_goal:
            logger.info(f"Selected highest-priority goal '{best_goal.id}' with priority {best_priority:.2f}")
            best_goal.metadata["selected_priority"] = best_priority
            # Track the generated goal
            self.generated_goals.append(best_goal)
        else:
            logger.warning("No suitable goal found among proposed goals")

        return best_goal

    def execute_with_feasibility_check(self, goal: Goal) -> bool:
        """
        Execute a goal after performing feasibility check.
        Returns True if goal was executed, False if blocked or adjusted.

        Args:
            goal: The goal to execute

        Returns:
            bool: Whether the goal was successfully executed
        """
        # Check if multi-file analysis is needed
        if self._needs_multi_file_analysis(goal):
            logger.info(f"Goal '{goal.id}' requires multi-file analysis")
            
            # Check if multi_file_refactoring capability is available
            if "multi_file_refactoring" in self.capabilities:
                logger.info(f"Using multi-file refactoring for goal '{goal.id}'")
                return self._execute_multi_file_refactoring(goal)
            else:
                logger.warning(f"Multi-file refactoring capability not available for goal '{goal.id}'")
                # Fall back to regular execution
                return self._execute_goal(goal)
        
        probability = self.estimator.estimate_success_probability(
            goal, self.capabilities, self.history
        )

        logger.info(f"Goal '{goal.id}' feasibility probability: {probability:.2f}")

        if probability < 0.2:
            reason = f"Feasibility probability {probability:.2f} below threshold 0.2"
            logger.warning(f"Blocking goal '{goal.id}': {reason}")
            self.blocked_goals.append((goal, reason))
            return False

        elif 0.2 <= probability < 0.5:
            logger.info(f"Adjusting goal '{goal.id}' due to low feasibility ({probability:.2f})")
            adjusted_goal = self._adjust_goal_complexity(goal)
            return self._execute_goal(adjusted_goal)

        else:
            logger.info(f"Executing goal '{goal.id}' with high feasibility ({probability:.2f})")
            return self._execute_goal(goal)

    def _adjust_goal_complexity(self, goal: Goal) -> Goal:
        """
        Adjust goal complexity by splitting into sub-goals or reducing scope.

        Args:
            goal: The goal to adjust

        Returns:
            Goal: Adjusted goal with reduced complexity
        """
        # Split into sub-goals if complexity is high
        if goal.complexity > 0.7:
            sub_goals = self._split_goal(goal)
            goal.sub_goals = sub_goals
            goal.complexity = 0.5  # Reduce complexity after splitting
            logger.info(f"Split goal '{goal.id}' into {len(sub_goals)} sub-goals")
        else:
            # Reduce scope by lowering complexity
            goal.complexity = min(goal.complexity * 0.7, 0.5)
            logger.info(f"Reduced complexity of goal '{goal.id}' to {goal.complexity:.2f}")

        return goal

    def _split_goal(self, goal: Goal) -> List[Goal]:
        """
        Split a complex goal into smaller sub-goals.

        Args:
            goal: The goal to split

        Returns:
            List[Goal]: List of sub-goals
        """
        # Simple splitting logic - can be enhanced based on goal structure
        sub_goals = []
        num_sub_goals = max(2, int(goal.complexity * 4))  # More sub-goals for higher complexity

        for i in range(num_sub_goals):
            sub_goal = Goal(
                id=f"{goal.id}_sub_{i}",
                description=f"Sub-goal {i+1} of {goal.description}",
                complexity=goal.complexity / num_sub_goals,
                metadata={"parent_goal_id": goal.id}
            )
            sub_goals.append(sub_goal)

        return sub_goals

    def _execute_goal(self, goal: Goal) -> bool:
        """
        Execute the actual goal logic.
        This is a placeholder for the real execution logic.

        Args:
            goal: The goal to execute

        Returns:
            bool: Whether execution was successful
        """
        # Placeholder for actual execution logic
        logger.info(f"Executing goal '{goal.id}': {goal.description}")

        # Execute sub-goals if they exist
        if goal.sub_goals:
            for sub_goal in goal.sub_goals:
                success = self._execute_goal(sub_goal)
                if not success:
                    logger.error(f"Sub-goal '{sub_goal.id}' failed")
                    return False

        # Update history with execution result
        self.history.append({
            "goal_id": goal.id,
            "description": goal.description,
            "complexity": goal.complexity,
            "status": "executed"
        })

        return True

    def add_to_queue(self, goal: Goal) -> None:
        """
        Add a goal to the execution queue after feasibility estimation.
        If blocked, log the decision and optionally trigger a capability acquisition sub-goal.
        The estimator's decision is recorded in the task metadata for future analysis.
        """
        # Check if queue is at maximum capacity
        if len(self.execution_queue) >= self.max_concurrent_goals:
            logger.warning(f"Execution queue is full ({self.max_concurrent_goals} goals), cannot add goal '{goal.id}'")
            return

        # Check if multi-file analysis is needed
        if self._needs_multi_file_analysis(goal):
            logger.info(f"Goal '{goal.id}' requires multi-file analysis")
            goal.metadata["multi_file_required"] = True
            
            # Check if multi_file_refactoring capability is available
            if "multi_file_refactoring" not in self.capabilities:
                logger.warning(f"Multi-file refactoring capability not available for goal '{goal.id}'")
                # Add capability acquisition sub-goal
                acquisition_goal = Goal(
                    id=f"{goal.id}_multi_file_capability_acquisition",
                    description=f"Acquire multi-file refactoring capability for {goal.description}",
                    complexity=0.4,
                    metadata={
                        "parent_goal_id": goal.id,
                        "type": "capability_acquisition",
                        "target_capability": "multi_file_refactoring"
                    }
                )
                logger.info(f"Triggering multi-file capability acquisition sub-goal '{acquisition_goal.id}'")
                self.execution_queue.append(acquisition_goal)
        
        # Perform feasibility estimation before enqueuing
        probability = self.estimator.estimate_success_probability(
            goal, self.capabilities, self.history
        )
        
        # Record the estimator's decision in the goal's metadata
        goal.metadata["feasibility_probability"] = probability
        goal.metadata["feasibility_threshold"] = 0.2
        goal.metadata["feasibility_decision"] = "blocked" if probability < 0.2 else "allowed"
        
        if probability < 0.2:
            reason = f"Feasibility probability {probability:.2f} below threshold 0.2"
            logger.warning(f"Blocking goal '{goal.id}' from queue: {reason}")
            self.blocked_goals.append((goal, reason))
            
            # Optionally trigger a capability acquisition sub-goal
            acquisition_goal = Goal(
                id=f"{goal.id}_capability_acquisition",
                description=f"Acquire capabilities needed for {goal.description}",
                complexity=0.3,
                metadata={
                    "parent_goal_id": goal.id,
                    "type": "capability_acquisition",
                    "original_feasibility": probability
                }
            )
            logger.info(f"Triggering capability acquisition sub-goal '{acquisition_goal.id}' for blocked goal '{goal.id}'")
            self.execution_queue.append(acquisition_goal)
        else:
            logger.info(f"Adding goal '{goal.id}' to execution queue with feasibility {probability:.2f}")
            self.execution_queue.append(goal)

    def process_queue(self) -> None:
        """Process all goals in the execution queue with integrated goal generation phase."""
        while self.execution_queue:
            goal = self.execution_queue.pop(0)
            self.execute_with_feasibility_check(goal)
            
            # Increment cycle count
            self.cycle_count += 1
            
            # After each reflection cycle, invoke the goal generator to propose new goals
            new_goal = self.generate_and_prioritize_goals()
            if new_goal:
                logger.info(f"New goal generated and prioritized: '{new_goal.id}'")
                self.add_to_queue(new_goal)
            
            # Goal generation phase: run after reflection based on frequency
            if self.cycle_count % self.goal_generation_frequency == 0:
                self._run_goal_generation_phase()

    def _run_goal_generation_phase(self) -> None:
        """
        Run the goal generation phase that generates new goals and feeds them into the execution queue.
        This phase runs after reflection cycles based on the configured frequency.
        """
        logger.info(f"Running goal generation phase at cycle {self.cycle_count}")
        
        # Generate multiple goals in this phase
        generated_goals = []
        for _ in range(self.goals_per_cycle):
            new_goal = self.generate_and_prioritize_goals()
            if new_goal:
                generated_goals.append(new_goal)
        
        # Feed generated goals back into the execution queue
        for goal in generated_goals:
            logger.info(f"Feeding generated goal '{goal.id}' into execution queue")
            self.add_to_queue(goal)
        
        if not generated_goals:
            logger.info("No new goals generated during goal generation phase")

    def get_blocked_goals(self) -> List[Tuple[Goal, str]]:
        """Get list of blocked goals with reasons."""
        return self.blocked_goals

    def clear_blocked_goals(self) -> None:
        """Clear the list of blocked goals."""
        self.blocked_goals.clear()
        logger.info("Cleared blocked goals list")

    def _needs_multi_file_analysis(self, goal: Goal) -> bool:
        """
        Check if a goal requires multi-file analysis based on its description and metadata.

        Args:
            goal: The goal to check

        Returns:
            bool: True if multi-file analysis is needed
        """
        # Check if the goal description mentions multiple files or cross-file changes
        multi_file_keywords = ["multiple files", "cross-file", "across files", "refactor", "restructure"]
        description_lower = goal.description.lower()
        
        if any(keyword in description_lower for keyword in multi_file_keywords):
            return True
        
        # Check metadata for explicit multi-file flag
        if goal.metadata.get("multi_file", False):
            return True
        
        # Check if goal has sub-goals that might require multi-file analysis
        if goal.sub_goals:
            for sub_goal in goal.sub_goals:
                if self._needs_multi_file_analysis(sub_goal):
                    return True
        
        return False

    def _execute_multi_file_refactoring(self, goal: Goal) -> bool:
        """
        Execute a multi-file refactoring goal.

        Args:
            goal: The multi-file refactoring goal to execute

        Returns:
            bool: Whether the refactoring was successful
        """
        logger.info(f"Executing multi-file refactoring for goal '{goal.id}': {goal.description}")
        
        # Create multi-file refactoring sub-goals
        refactoring_sub_goals = [
            Goal(
                id=f"{goal.id}_analyze",
                description=f"Analyze files for {goal.description}",
                complexity=0.3,
                metadata={"type": "multi_file_analysis", "parent_goal_id": goal.id}
            ),
            Goal(
                id=f"{goal.id}_refactor",
                description=f"Perform refactoring for {goal.description}",
                complexity=0.5,
                metadata={"type": "multi_file_refactoring", "parent_goal_id": goal.id}
            ),
            Goal(
                id=f"{goal.id}_verify",
                description=f"Verify refactoring results for {goal.description}",
                complexity=0.2,
                metadata={"type": "verification", "parent_goal_id": goal.id}
            )
        ]
        
        # Execute the sub-goals
        for sub_goal in refactoring_sub_goals:
            success = self._execute_goal(sub_goal)
            if not success:
                logger.error(f"Multi-file refactoring sub-goal '{sub_goal.id}' failed")
                return False
        
        # Update history with multi-file refactoring result
        self.history.append({
            "goal_id": goal.id,
            "description": goal.description,
            "type": "multi_file_refactoring",
            "status": "completed",
            "sub_goals": [sg.id for sg in refactoring_sub_goals]
        })
        
        return True