import os
import sys
import tempfile
import importlib.util
import unittest
from unittest.mock import MagicMock, patch

# Add the project root to sys.path if needed
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from core.environmental_pressure import TestSuiteMutator, EnvironmentalPressure


class TestTestSuiteMutation(unittest.TestCase):
    """Test suite for TestSuiteMutator self-modification capabilities."""

    def setUp(self):
        """Set up a temporary directory for test file generation."""
        self.temp_dir = tempfile.mkdtemp()
        self.mutator = TestSuiteMutator(output_dir=self.temp_dir)

    def tearDown(self):
        """Clean up temporary files."""
        import shutil
        shutil.rmtree(self.temp_dir, ignore_errors=True)

    def test_mutator_generates_importable_file(self):
        """Test that TestSuiteMutator generates a valid, importable Python file."""
        # (1) Register a mock pressure
        mock_pressure = MagicMock(spec=EnvironmentalPressure)
        mock_pressure.name = "mock_pressure"
        mock_pressure.description = "A mock pressure for testing"
        mock_pressure.generate_test_code.return_value = (
            "def test_mock_pressure():\n"
            '    """Test generated by mock pressure."""\n'
            "    assert True\n"
        )
        self.mutator.register_pressure(mock_pressure)

        # (2) Call mutate() to generate a new test file
        output_filename = "generated_test_mock.py"
        result_path = self.mutator.mutate(output_filename=output_filename)

        # (3) Verify the file exists and can be imported without errors
        self.assertTrue(os.path.exists(result_path), f"Generated file {result_path} does not exist")

        # Attempt to import the generated module
        spec = importlib.util.spec_from_file_location("generated_test_mock", result_path)
        module = importlib.util.module_from_spec(spec)
        try:
            spec.loader.exec_module(module)
        except Exception as e:
            self.fail(f"Generated file could not be imported: {e}")

        # Verify the expected test function exists in the module
        self.assertTrue(hasattr(module, "test_mock_pressure"),
                        "Generated module does not contain expected test function")

        # Verify the mock pressure's generate_test_code was called
        mock_pressure.generate_test_code.assert_called_once()

    def test_mutator_with_multiple_pressures(self):
        """Test that mutator handles multiple registered pressures correctly."""
        # Register two mock pressures
        mock_pressure1 = MagicMock(spec=EnvironmentalPressure)
        mock_pressure1.name = "pressure_one"
        mock_pressure1.description = "First mock pressure"
        mock_pressure1.generate_test_code.return_value = (
            "def test_pressure_one():\n"
            '    """Test from pressure one."""\n'
            "    assert 1 + 1 == 2\n"
        )

        mock_pressure2 = MagicMock(spec=EnvironmentalPressure)
        mock_pressure2.name = "pressure_two"
        mock_pressure2.description = "Second mock pressure"
        mock_pressure2.generate_test_code.return_value = (
            "def test_pressure_two():\n"
            '    """Test from pressure two."""\n'
            "    assert 2 * 2 == 4\n"
        )

        self.mutator.register_pressure(mock_pressure1)
        self.mutator.register_pressure(mock_pressure2)

        output_filename = "generated_test_multi.py"
        result_path = self.mutator.mutate(output_filename=output_filename)

        self.assertTrue(os.path.exists(result_path))

        # Import and verify both functions exist
        spec = importlib.util.spec_from_file_location("generated_test_multi", result_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        self.assertTrue(hasattr(module, "test_pressure_one"))
        self.assertTrue(hasattr(module, "test_pressure_two"))

        # Verify both pressures were called
        mock_pressure1.generate_test_code.assert_called_once()
        mock_pressure2.generate_test_code.assert_called_once()

    def test_mutator_handles_empty_pressure_list(self):
        """Test that mutator handles no registered pressures gracefully."""
        output_filename = "generated_test_empty.py"
        result_path = self.mutator.mutate(output_filename=output_filename)

        self.assertTrue(os.path.exists(result_path))

        # Import should work even with no tests
        spec = importlib.util.spec_from_file_location("generated_test_empty", result_path)
        module = importlib.util.module_from_spec(spec)
        try:
            spec.loader.exec_module(module)
        except Exception as e:
            self.fail(f"Empty generated file could not be imported: {e}")

    def test_mutator_preserves_existing_file(self):
        """Test that mutator does not overwrite existing file without explicit intent."""
        # Create an existing file
        existing_file = os.path.join(self.temp_dir, "existing_test.py")
        with open(existing_file, "w") as f:
            f.write("# Existing test file\n")

        # Register a mock pressure
        mock_pressure = MagicMock(spec=EnvironmentalPressure)
        mock_pressure.name = "mock"
        mock_pressure.description = "Mock"
        mock_pressure.generate_test_code.return_value = "def test_new(): pass\n"
        self.mutator.register_pressure(mock_pressure)

        # Attempt to mutate with the same filename (should raise or handle gracefully)
        with self.assertRaises(FileExistsError):
            self.mutator.mutate(output_filename="existing_test.py")


if __name__ == "__main__":
    unittest.main()