import os
import sys
import unittest
import subprocess
import tempfile
import importlib.util

# Hardcoded path to the project root (adjust if needed)
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))


class TestEcologyBootstrap(unittest.TestCase):
    """Minimal bootstrap test for the ecology system."""

    def setUp(self):
        # Ensure the project root is in sys.path
        if PROJECT_ROOT not in sys.path:
            sys.path.insert(0, PROJECT_ROOT)

    def test_generate_valid_benchmark(self):
        """Test that generate_valid_benchmark() creates a valid test file."""
        from core.ecology_engine import generate_valid_benchmark

        # Use a temporary directory to avoid polluting the project
        with tempfile.TemporaryDirectory() as tmpdir:
            # Change to temp dir for generation
            original_cwd = os.getcwd()
            os.chdir(tmpdir)
            try:
                # Generate the benchmark file
                generate_valid_benchmark()

                # Check that a .py file was created
                py_files = [f for f in os.listdir(tmpdir) if f.endswith('.py')]
                self.assertGreater(len(py_files), 0,
                                   "No Python file generated by generate_valid_benchmark()")

                # Try to import the generated file
                generated_file = os.path.join(tmpdir, py_files[0])
                spec = importlib.util.spec_from_file_location("generated_test", generated_file)
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)

                # Run the generated test if it contains a test class
                if hasattr(module, 'TestGenerated'):
                    result = subprocess.run(
                        [sys.executable, '-m', 'unittest', 'generated_test.TestGenerated'],
                        capture_output=True, text=True, cwd=tmpdir
                    )
                    self.assertEqual(result.returncode, 0,
                                     f"Generated test failed:\n{result.stderr}")
            finally:
                os.chdir(original_cwd)

    def test_environmental_pressure_generation(self):
        """Test that environmental_pressure can generate at least one pressure file."""
        from core.environmental_pressure import generate_pressure_files

        with tempfile.TemporaryDirectory() as tmpdir:
            original_cwd = os.getcwd()
            os.chdir(tmpdir)
            try:
                # Generate pressure files
                generate_pressure_files()

                # Check that at least one pressure file was created
                pressure_files = [f for f in os.listdir(tmpdir) if 'pressure' in f.lower()]
                self.assertGreater(len(pressure_files), 0,
                                   "No pressure files generated by environmental_pressure")
            finally:
                os.chdir(original_cwd)

    def test_import_ecology_engine(self):
        """Test that core.ecology_engine can be imported without errors."""
        try:
            import core.ecology_engine
            self.assertTrue(hasattr(core.ecology_engine, 'generate_valid_benchmark'))
        except ImportError as e:
            self.fail(f"Failed to import core.ecology_engine: {e}")

    def test_import_environmental_pressure(self):
        """Test that environmental_pressure module can be imported without errors."""
        try:
            import core.environmental_pressure
            self.assertTrue(hasattr(core.environmental_pressure, 'generate_pressure_files'))
        except ImportError as e:
            self.fail(f"Failed to import core.environmental_pressure: {e}")


if __name__ == '__main__':
    unittest.main()