import os
import re
import json
import ast
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field, asdict
from pathlib import Path
from collections import defaultdict

# ------------------------------------------------------------------------------
# Data structures
# ------------------------------------------------------------------------------

@dataclass
class ResearchTopic:
    """Represents a research topic with its taxonomy and search patterns."""
    name: str
    category: str          # e.g., 'codec', 'protocol', 'algorithm', 'system'
    aliases: List[str] = field(default_factory=list)
    keywords: List[str] = field(default_factory=list)
    search_patterns: List[str] = field(default_factory=list)
    related_topics: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ResearchTopic':
        return cls(**data)


@dataclass
class CodeSnippet:
    """Represents a relevant code snippet found in the knowledge base."""
    file_path: str
    line_start: int
    line_end: int
    content: str
    language: str = 'python'
    relevance_score: float = 0.0
    tags: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class AlgorithmAnalysis:
    """Holds analysis of an algorithm implementation."""
    name: str
    module_path: str
    complexity: str          # e.g., 'O(n)', 'O(n log n)'
    description: str
    input_output: str
    dependencies: List[str] = field(default_factory=list)
    code_snippets: List[CodeSnippet] = field(default_factory=list)
    technical_principles: List[str] = field(default_factory=list)
    application_scenarios: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ResearchReport:
    """Complete research report generated by the engine."""
    topic: str
    summary: str
    technical_principles: List[str] = field(default_factory=list)
    algorithm_details: List[AlgorithmAnalysis] = field(default_factory=list)
    application_scenarios: List[str] = field(default_factory=list)
    related_topics: List[str] = field(default_factory=list)
    references: List[str] = field(default_factory=list)
    code_examples: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_markdown(self) -> str:
        """Render the report as a structured Markdown document."""
        lines = []
        lines.append(f"# Research Report: {self.topic}")
        lines.append("")
        lines.append("## Summary")
        lines.append(self.summary)
        lines.append("")
        if self.technical_principles:
            lines.append("## Technical Principles")
            for p in self.technical_principles:
                lines.append(f"- {p}")
            lines.append("")
        if self.algorithm_details:
            lines.append("## Algorithm Details")
            for algo in self.algorithm_details:
                lines.append(f"### {algo.name}")
                lines.append(f"**Module:** `{algo.module_path}`")
                lines.append(f"**Complexity:** {algo.complexity}")
                lines.append(f"**Description:** {algo.description}")
                lines.append(f"**Input/Output:** {algo.input_output}")
                if algo.dependencies:
                    lines.append(f"**Dependencies:** {', '.join(algo.dependencies)}")
                if algo.technical_principles:
                    lines.append("**Principles:**")
                    for pr in algo.technical_principles:
                        lines.append(f"- {pr}")
                if algo.application_scenarios:
                    lines.append("**Scenarios:**")
                    for sc in algo.application_scenarios:
                        lines.append(f"- {sc}")
                lines.append("")
        if self.application_scenarios:
            lines.append("## Application Scenarios")
            for sc in self.application_scenarios:
                lines.append(f"- {sc}")
            lines.append("")
        if self.code_examples:
            lines.append("## Code Examples")
            for ex in self.code_examples:
                lines.append("```python")
                lines.append(ex)
                lines.append("```")
                lines.append("")
        if self.related_topics:
            lines.append("## Related Topics")
            for rt in self.related_topics:
                lines.append(f"- {rt}")
            lines.append("")
        if self.references:
            lines.append("## References")
            for ref in self.references:
                lines.append(f"- {ref}")
            lines.append("")
        return "\n".join(lines)


# ------------------------------------------------------------------------------
# Topic taxonomy mapping
# ------------------------------------------------------------------------------

TOPIC_TAXONOMY: Dict[str, ResearchTopic] = {
    'AEC': ResearchTopic(
        name='AEC',
        category='algorithm',
        aliases=['acoustic echo cancellation', 'echo cancellation'],
        keywords=['aec', 'echo', 'acoustic', 'nlms', 'adaptive filter', 'double talk'],
        search_patterns=[
            r'\baec\b', r'echo\s+cancell', r'acoustic\s+echo',
            r'adaptive\s+filter', r'NLMS', r'double\s+talk'
        ],
        related_topics=['ANS', 'AGC', 'VAD']
    ),
    'ANS': ResearchTopic(
        name='ANS',
        category='algorithm',
        aliases=['active noise suppression', 'noise reduction'],
        keywords=['ans', 'noise', 'suppression', 'spectral subtraction', 'wiener filter'],
        search_patterns=[
            r'\bans\b', r'noise\s+suppress', r'noise\s+reduction',
            r'spectral\s+subtraction', r'wiener\s+filter'
        ],
        related_topics=['AEC', 'AGC', 'VAD']
    ),
    'AGC': ResearchTopic(
        name='AGC',
        category='algorithm',
        aliases=['automatic gain control'],
        keywords=['agc', 'gain', 'volume', 'leveler'],
        search_patterns=[
            r'\bagc\b', r'automatic\s+gain', r'gain\s+control',
            r'volume\s+level'
        ],
        related_topics=['AEC', 'ANS']
    ),
    'VAD': ResearchTopic(
        name='VAD',
        category='algorithm',
        aliases=['voice activity detection'],
        keywords=['vad', 'voice', 'activity', 'speech detection'],
        search_patterns=[
            r'\bvad\b', r'voice\s+activity', r'speech\s+detection'
        ],
        related_topics=['AEC', 'ANS']
    ),
    'H264': ResearchTopic(
        name='H264',
        category='codec',
        aliases=['h.264', 'avc', 'advanced video coding'],
        keywords=['h264', 'h.264', 'avc', 'video codec', 'encoding', 'decoding'],
        search_patterns=[
            r'\bh264\b', r'h\.264', r'\bavc\b', r'advanced\s+video\s+coding',
            r'macroblock', r'motion\s+estimation', r'deblocking'
        ],
        related_topics=['H265', 'VP9', 'AV1']
    ),
    'H265': ResearchTopic(
        name='H265',
        category='codec',
        aliases=['h.265', 'hevc', 'high efficiency video coding'],
        keywords=['h265', 'h.265', 'hevc', 'video codec'],
        search_patterns=[
            r'\bh265\b', r'h\.265', r'\bhevc\b', r'high\s+efficiency\s+video'
        ],
        related_topics=['H264', 'VP9', 'AV1']
    ),
    'RTP': ResearchTopic(
        name='RTP',
        category='protocol',
        aliases=['real-time transport protocol'],
        keywords=['rtp', 'real-time', 'transport', 'streaming', 'udp'],
        search_patterns=[
            r'\brtp\b', r'real-time\s+transport', r'rtp\s+packet',
            r'rtp\s+payload', r'rtcp'
        ],
        related_topics=['SRTP', 'RTSP', 'SDP']
    ),
    'SRTP': ResearchTopic(
        name='SRTP',
        category='protocol',
        aliases=['secure real-time transport protocol'],
        keywords=['srtp', 'secure', 'encryption', 'authentication'],
        search_patterns=[
            r'\bsrtp\b', r'secure\s+rtp', r'srtp\s+encrypt'
        ],
        related_topics=['RTP', 'RTSP']
    ),
    'RTSP': ResearchTopic(
        name='RTSP',
        category='protocol',
        aliases=['real-time streaming protocol'],
        keywords=['rtsp', 'streaming', 'control', 'media session'],
        search_patterns=[
            r'\brtsp\b', r'real-time\s+streaming', r'rtsp\s+session'
        ],
        related_topics=['RTP', 'SRTP']
    ),
    'SDP': ResearchTopic(
        name='SDP',
        category='protocol',
        aliases=['session description protocol'],
        keywords=['sdp', 'session', 'description', 'media negotiation'],
        search_patterns=[
            r'\bsdp\b', r'session\s+description', r'sdp\s+offer'
        ],
        related_topics=['RTP', 'RTSP']
    ),
    'FFT': ResearchTopic(
        name='FFT',
        category='algorithm',
        aliases=['fast fourier transform'],
        keywords=['fft', 'fourier', 'transform', 'frequency'],
        search_patterns=[
            r'\bfft\b', r'fast\s+fourier', r'fourier\s+transform'
        ],
        related_topics=['DCT', 'MDCT', 'STFT']
    ),
    'DCT': ResearchTopic(
        name='DCT',
        category='algorithm',
        aliases=['discrete cosine transform'],
        keywords=['dct', 'cosine', 'transform'],
        search_patterns=[
            r'\bdct\b', r'discrete\s+cosine', r'cosine\s+transform'
        ],
        related_topics=['FFT', 'MDCT']
    ),
    'MDCT': ResearchTopic(
        name='MDCT',
        category='algorithm',
        aliases=['modified discrete cosine transform'],
        keywords=['mdct', 'modified', 'cosine', 'transform'],
        search_patterns=[
            r'\bmdct\b', r'modified\s+discrete\s+cosine'
        ],
        related_topics=['FFT', 'DCT']
    ),
    'STFT': ResearchTopic(
        name='STFT',
        category='algorithm',
        aliases=['short-time fourier transform'],
        keywords=['stft', 'short-time', 'fourier', 'spectrogram'],
        search_patterns=[
            r'\bstft\b', r'short-time\s+fourier', r'spectrogram'
        ],
        related_topics=['FFT', 'DCT']
    ),
    'ADPCM': ResearchTopic(
        name='ADPCM',
        category='codec',
        aliases=['adaptive differential pulse code modulation'],
        keywords=['adpcm', 'pcm', 'differential', 'adaptive'],
        search_patterns=[
            r'\badpcm\b', r'adaptive\s+differential', r'pulse\s+code\s+modulation'
        ],
        related_topics=['PCM', 'G711', 'G726']
    ),
    'G711': ResearchTopic(
        name='G711',
        category='codec',
        aliases=['g.711', 'mu-law', 'a-law'],
        keywords=['g711', 'g.711', 'mu-law', 'a-law', 'pcm'],
        search_patterns=[
            r'\bg711\b', r'g\.711', r'mu-law', r'a-law'
        ],
        related_topics=['ADPCM', 'G726', 'PCM']
    ),
    'G726': ResearchTopic(
        name='G726',
        category='codec',
        aliases=['g.726', 'adpcm'],
        keywords=['g726', 'g.726', 'adpcm'],
        search_patterns=[
            r'\bg726\b', r'g\.726'
        ],
        related_topics=['ADPCM', 'G711']
    ),
    'PCM': ResearchTopic(
        name='PCM',
        category='codec',
        aliases=['pulse code modulation'],
        keywords=['pcm', 'pulse', 'code', 'modulation', 'audio'],
        search_patterns=[
            r'\bpcm\b', r'pulse\s+code\s+modulation'
        ],
        related_topics=['ADPCM', 'G711', 'G726']
    ),
    'RTCP': ResearchTopic(
        name='RTCP',
        category='protocol',
        aliases=['real-time transport control protocol'],
        keywords=['rtcp', 'control', 'feedback', 'qos', 'statistics'],
        search_patterns=[
            r'\brtcp\b', r'real-time\s+control', r'rtcp\s+packet',
            r'rtcp\s+report', r'sender\s+report', r'receiver\s+report'
        ],
        related_topics=['RTP', 'SRTP', 'RTSP']
    ),
    'VP9': ResearchTopic(
        name='VP9',
        category='codec',
        aliases=['vp9', 'google vp9'],
        keywords=['vp9', 'google', 'video codec', 'open source'],
        search_patterns=[
            r'\bvp9\b', r'vp9\s+codec', r'google\s+vp9'
        ],
        related_topics=['H264', 'H265', 'AV1']
    ),
    'AV1': ResearchTopic(
        name='AV1',
        category='codec',
        aliases=['av1', 'aomedia video 1'],
        keywords=['av1', 'aomedia', 'video codec', 'royalty-free'],
        search_patterns=[
            r'\bav1\b', r'av1\s+codec', r'aomedia\s+video'
        ],
        related_topics=['H264', 'H265', 'VP9']
    ),
}


# ------------------------------------------------------------------------------
# Core engine
# ------------------------------------------------------------------------------

class AVResearchEngine:
    """
    Core research engine for audio/video topics.
    Scans the knowledge base, analyzes implementations, and generates structured reports.
    """

    def __init__(self, knowledge_base_path: str = '.'):
        self.kb_path = Path(knowledge_base_path)
        self.taxonomy = TOPIC_TAXONOMY
        self._cache: Dict[str, List[CodeSnippet]] = {}
        self._reports_dir = Path('reports/av-research')
        self._reports_dir.mkdir(parents=True, exist_ok=True)

    # --------------------------------------------------------------------------
    # Public API
    # --------------------------------------------------------------------------

    def research(self, topic: str, output_format: str = 'markdown') -> str:
        """
        Perform research on a given topic.
        
        Args:
            topic: The research topic (e.g., 'AEC', 'ANS', 'H264', 'RTP')
            output_format: 'markdown' or 'json'
        
        Returns:
            A structured research report as a string.
        """
        topic_info = self._resolve_topic(topic)
        if topic_info is None:
            return f"Error: Unknown topic '{topic}'. Available topics: {list(self.taxonomy.keys())}"

        # 1. Scan knowledge base
        snippets = self._scan_knowledge_base(topic_info)

        # 2. Analyze algorithms
        algorithms = self._analyze_algorithms(snippets, topic_info)

        # 3. Generate report
        report = self._generate_report(topic_info, snippets, algorithms)

        # 4. Write report to file
        self._write_report(report, topic_info.name)

        if output_format == 'json':
            return json.dumps(report.to_dict(), indent=2)
        else:
            return report.to_markdown()

    def research_multiple(self, topics: List[str], output_format: str = 'markdown') -> Dict[str, str]:
        """
        Perform research on multiple topics.
        
        Args:
            topics: List of research topics
            output_format: 'markdown' or 'json'
        
        Returns:
            Dictionary mapping topic names to their reports.
        """
        results = {}
        for topic in topics:
            result = self.research(topic, output_format)
            results[topic] = result
        return results

    def list_topics(self) -> List[str]:
        """Return all known topic names."""
        return list(self.taxonomy.keys())

    def get_topic_info(self, topic: str) -> Optional[Dict[str, Any]]:
        """Get detailed info about a topic."""
        t = self._resolve_topic(topic)
        if t:
            return t.to_dict()
        return None

    def add_topic(self, topic: ResearchTopic) -> None:
        """Add a custom topic to the taxonomy."""
        self.taxonomy[topic.name] = topic

    def scan_knowledge_base(self, topic: str) -> List[CodeSnippet]:
        """
        Public method to scan knowledge base for a topic.
        
        Args:
            topic: The research topic name
        
        Returns:
            List of relevant code snippets.
        """
        topic_info = self._resolve_topic(topic)
        if topic_info is None:
            return []
        return self._scan_knowledge_base(topic_info)

    # --------------------------------------------------------------------------
    # Internal helpers
    # --------------------------------------------------------------------------

    def _resolve_topic(self, name: str) -> Optional[ResearchTopic]:
        """Resolve a topic name (case-insensitive, check aliases)."""
        name_lower = name.lower().strip()
        # Direct match
        if name.upper() in self.taxonomy:
            return self.taxonomy[name.upper()]
        # Check aliases
        for key, topic in self.taxonomy.items():
            if name_lower == key.lower():
                return topic
            for alias in topic.aliases:
                if name_lower == alias.lower():
                    return topic
        return None

    def _scan_knowledge_base(self, topic: ResearchTopic) -> List[CodeSnippet]:
        """
        Scan the knowledge base directory for files matching the topic's search patterns.
        Returns a list of relevant code snippets.
        """
        if topic.name in self._cache:
            return self._cache[topic.name]

        snippets: List[CodeSnippet] = []
        patterns = topic.search_patterns
        compiled_patterns = [re.compile(p, re.IGNORECASE) for p in patterns]

        # Walk through all Python files in the knowledge base
        for file_path in self.kb_path.rglob('*.py'):
            try:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    lines = f.readlines()
            except Exception:
                continue

            rel_path = str(file_path.relative_to(self.kb_path))
            for i, line in enumerate(lines, start=1):
                for pattern in compiled_patterns:
                    if pattern.search(line):
                        # Extract a snippet around the matched line
                        start = max(0, i - 3)
                        end = min(len(lines), i + 3)
                        snippet_content = ''.join(lines[start:end])
                        snippet = CodeSnippet(
                            file_path=rel_path,
                            line_start=start + 1,
                            line_end=end,
                            content=snippet_content.strip(),
                            relevance_score=1.0,
                            tags=[topic.name]
                        )
                        snippets.append(snippet)
                        break  # avoid duplicate matches for same line

        self._cache[topic.name] = snippets
        return snippets

    def _analyze_algorithms(
        self, snippets: List[CodeSnippet], topic: ResearchTopic
    ) -> List[AlgorithmAnalysis]:
        """
        Analyze code snippets to extract algorithm details.
        Uses AST parsing to understand function signatures and docstrings.
        """
        algorithms: Dict[str, AlgorithmAnalysis] = {}

        for snippet in snippets:
            file_path = self.kb_path / snippet.file_path
            try:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    source = f.read()
            except Exception:
                continue

            try:
                tree = ast.parse(source)
            except SyntaxError:
                continue

            # Find functions/classes that match the topic
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    func_name = node.name
                    # Check if function name or docstring matches topic keywords
                    if any(kw.lower() in func_name.lower() for kw in topic.keywords):
                        # Extract function details
                        docstring = ast.get_docstring(node) or ''
                        complexity = self._estimate_complexity(node)
                        description = docstring.split('\n')[0] if docstring else f"Function {func_name} related to {topic.name}"
                        input_output = self._extract_input_output(node)
                        
                        if func_name not in algorithms:
                            algorithms[func_name] = AlgorithmAnalysis(
                                name=func_name,
                                module_path=snippet.file_path,
                                complexity=complexity,
                                description=description,
                                input_output=input_output,
                                dependencies=self._extract_dependencies(node),
                                code_snippets=[snippet],
                                technical_principles=self._extract_principles(docstring, topic),
                                application_scenarios=self._extract_scenarios(docstring, topic)
                            )
                        else:
                            algorithms[func_name].code_snippets.append(snippet)

        return list(algorithms.values())

    def _estimate_complexity(self, node: ast.FunctionDef) -> str:
        """Estimate time complexity based on nested loops."""
        loops = 0
        for child in ast.walk(node):
            if isinstance(child, (ast.For, ast.While)):
                loops += 1
        if loops == 0:
            return 'O(1)'
        elif loops == 1:
            return 'O(n)'
        elif loops == 2:
            return 'O(n²)'
        else:
            return f'O(n^{loops})'

    def _extract_input_output(self, node: ast.FunctionDef) -> str:
        """Extract input/output description from function signature."""
        args = [arg.arg for arg in node.args.args if arg.arg != 'self']
        returns = ast.get_docstring(node) or ''
        # Try to find return description in docstring
        return_match = re.search(r'Returns?:?\s*(.*?)(?:\n|$)', returns)
        return_desc = return_match.group(1) if return_match else 'Unknown'
        return f"Inputs: {', '.join(args) if args else 'None'}; Output: {return_desc}"

    def _extract_dependencies(self, node: ast.FunctionDef) -> List[str]:
        """Extract module dependencies from function body."""
        deps = set()
        for child in ast.walk(node):
            if isinstance(child, ast.Call):
                if isinstance(child.func, ast.Attribute):
                    deps.add(child.func.attr)
                elif isinstance(child.func, ast.Name):
                    deps.add(child.func.id)
        return list(deps)[:5]  # Limit to top 5 dependencies

    def _extract_principles(self, docstring: str, topic: ResearchTopic) -> List[str]:
        """Extract technical principles from docstring."""
        principles = []
        if docstring:
            # Look for sections describing principles
            principle_match = re.search(r'Principles?:?\s*(.*?)(?:\n\n|$)', docstring, re.DOTALL)
            if principle_match:
                principles = [p.strip() for p in principle_match.group(1).split('\n') if p.strip()]
        # Add topic-specific principles if none found
        if not principles:
            principles = [
                f"Based on {topic.name} standard specifications",
                f"Implements core {topic.name} algorithms",
                f"Optimized for real-time processing"
            ]
        return principles

    def _extract_scenarios(self, docstring: str, topic: ResearchTopic) -> List[str]:
        """Extract application scenarios from docstring."""
        scenarios = []
        if docstring:
            scenario_match = re.search(r'Scenarios?:?\s*(.*?)(?:\n\n|$)', docstring, re.DOTALL)
            if scenario_match:
                scenarios = [s.strip() for s in scenario_match.group(1).split('\n') if s.strip()]
        # Add topic-specific scenarios if none found
        if not scenarios:
            scenarios = [
                f"Real-time {topic.category} processing",
                f"Integration with {topic.name} systems",
                f"Performance optimization for {topic.name}"
            ]
        return scenarios

    def _generate_report(
        self, topic: ResearchTopic, snippets: List[CodeSnippet], 
        algorithms: List[AlgorithmAnalysis]
    ) -> ResearchReport:
        """Generate a structured research report."""
        # Build summary
        summary = f"Research report for {topic.name} ({topic.category}). "
        summary += f"Found {len(snippets)} relevant code snippets and {len(algorithms)} algorithm implementations. "
        summary += f"Related topics: {', '.join(topic.related_topics)}."

        # Build technical principles
        technical_principles = []
        if algorithms:
            for algo in algorithms:
                technical_principles.extend(algo.technical_principles)
        if not technical_principles:
            technical_principles = [
                f"{topic.name} is a {topic.category} technology used in audio/video processing",
                f"Implements standard algorithms for {topic.name.lower()}",
                f"Optimized for low-latency real-time applications"
            ]

        # Build application scenarios
        application_scenarios = []
        if algorithms:
            for algo in algorithms:
                application_scenarios.extend(algo.application_scenarios)
        if not application_scenarios:
            application_scenarios = [
                f"Real-time {topic.category} processing in communication systems",
                f"Integration with multimedia frameworks",
                f"Performance-critical audio/video pipelines"
            ]

        # Build code examples
        code_examples = []
        for snippet in snippets[:3]:  # Limit to top 3 snippets
            code_examples.append(snippet.content)

        # Build references
        references = []
        for snippet in snippets:
            ref = f"File: {snippet.file_path} (lines {snippet.line_start}-{snippet.line_end})"
            if ref not in references:
                references.append(ref)

        return ResearchReport(
            topic=topic.name,
            summary=summary,
            technical_principles=technical_principles,
            algorithm_details=algorithms,
            application_scenarios=application_scenarios,
            related_topics=topic.related_topics,
            references=references,
            code_examples=code_examples,
            metadata={
                'category': topic.category,
                'keywords': topic.keywords,
                'snippet_count': len(snippets),
                'algorithm_count': len(algorithms)
            }
        )

    def _write_report(self, report: ResearchReport, topic_name: str) -> None:
        """Write the report to a markdown file in the reports directory."""
        # Create topic-specific directory
        topic_dir = self._reports_dir / topic_name.lower()
        topic_dir.mkdir(parents=True, exist_ok=True)

        # Write markdown report
        report_file = topic_dir / f"{topic_name.lower()}_report.md"
        with open(report_file, 'w', encoding='utf-8') as f:
            f.write(report.to_markdown())

        # Write JSON version for programmatic access
        json_file = topic_dir / f"{topic_name.lower()}_report.json"
        with open(json_file, 'w', encoding='utf-8') as f:
            json.dump(report.to_dict(), f, indent=2)

    def generate_index(self) -> str:
        """Generate an index of all available reports."""
        index_lines = ["# AV Research Reports Index", ""]
        for topic_name in sorted(self.taxonomy.keys()):
            topic = self.taxonomy[topic_name]
            report_path = self._reports_dir / topic_name.lower() / f"{topic_name.lower()}_report.md"
            if report_path.exists():
                index_lines.append(f"- [{topic_name} ({topic.category})]({report_path})")
            else:
                index_lines.append(f"- [{topic_name} ({topic.category})] - No report generated yet")
        return "\n".join(index_lines)

    def write_index(self) -> None:
        """Write the index file to the reports directory."""
        index_content = self.generate_index()
        index_file = self._reports_dir / "INDEX.md"
        with open(index_file, 'w', encoding='utf-8') as f:
            f.write(index_content)