"""
Ecology Engine: Mutates the fitness landscape by injecting new test cases and benchmarks.
Integrates with the evolution orchestrator via a mutate_fitness_landscape hook.
Uses only standard library modules: os, json, random, hashlib, collections.
"""

import os
import json
import random
import hashlib
import collections
from typing import Dict, List, Optional, Set, Tuple


class TestSuiteMutator:
    """Mutates the test suite by scanning, generating, and modifying test files."""
    
    def __init__(self, test_dir: str = "tests"):
        self.test_dir = test_dir
        self.existing_tests: List[str] = []
        self._scan_existing_tests()
    
    def _scan_existing_tests(self) -> List[str]:
        """Scan the tests/ directory for existing test files."""
        test_files = []
        if os.path.isdir(self.test_dir):
            for fname in os.listdir(self.test_dir):
                if fname.startswith("test_") and fname.endswith(".py"):
                    test_files.append(os.path.join(self.test_dir, fname))
        self.existing_tests = sorted(test_files)
        return test_files
    
    def generate_new_test(self) -> str:
        """Create a simple new test file with a unique name."""
        timestamp = hashlib.md5(str(random.random()).encode()).hexdigest()[:8]
        filename = f"test_ecology_{timestamp}.py"
        filepath = os.path.join(self.test_dir, filename)
        
        content = [
            "import pytest",
            "",
            "",
            f"def test_{timestamp}_basic():",
            "    \"\"\"Basic test generated by Ecology Engine.\"\"\"",
            "    assert True",
            "",
            "",
            f"def test_{timestamp}_value():",
            "    \"\"\"Value test generated by Ecology Engine.\"\"\"",
            "    result = 42",
            "    assert result == 42",
            "",
        ]
        
        os.makedirs(self.test_dir, exist_ok=True)
        with open(filepath, "w") as f:
            f.write("\n".join(content))
        
        self._scan_existing_tests()
        return filepath
    
    def mutate_existing_test(self) -> Optional[str]:
        """Append a new test case to an existing test file."""
        self._scan_existing_tests()
        if not self.existing_tests:
            return None
        
        target_file = random.choice(self.existing_tests)
        timestamp = hashlib.md5(str(random.random()).encode()).hexdigest()[:8]
        
        new_test_case = [
            "",
            "",
            f"def test_mutated_{timestamp}():",
            "    \"\"\"Mutated test case appended by Ecology Engine.\"\"\"",
            "    assert True",
            "",
        ]
        
        with open(target_file, "a") as f:
            f.write("\n".join(new_test_case))
        
        return target_file
    
    def get_test_suite_diversity(self) -> int:
        """Return the number of unique test file prefixes."""
        self._scan_existing_tests()
        prefixes = set()
        for test_file in self.existing_tests:
            basename = os.path.basename(test_file)
            if basename.startswith("test_"):
                parts = basename.split("_")
                if len(parts) >= 2:
                    prefix = parts[1]
                    prefixes.add(prefix)
        return len(prefixes)


class TestSuiteEvolver:
    """Maintains a registry of test types and their diversity score."""
    
    def __init__(self):
        self.test_registry: Dict[str, float] = {
            "unit": 0.0,
            "integration": 0.0,
            "stress": 0.0,
            "adversarial": 0.0,
            "edge_case": 0.0
        }
        self.module_coverage: Dict[str, Set[str]] = {}
        self.environmental_pressures: List[Dict] = []
    
    def register_test_type(self, test_type: str, diversity_score: float = 0.5) -> None:
        """Register a new test type with its diversity score."""
        self.test_registry[test_type] = diversity_score
    
    def update_diversity_score(self, test_type: str, score: float) -> None:
        """Update the diversity score for a test type."""
        if test_type in self.test_registry:
            self.test_registry[test_type] = score
    
    def get_diversity_score(self, test_type: str) -> float:
        """Get the diversity score for a test type."""
        return self.test_registry.get(test_type, 0.0)
    
    def track_module_test(self, module_name: str, test_type: str) -> None:
        """Track which modules are tested by which test types."""
        if module_name not in self.module_coverage:
            self.module_coverage[module_name] = set()
        self.module_coverage[module_name].add(test_type)
    
    def get_modules_for_test_type(self, test_type: str) -> List[str]:
        """Get all modules tested by a specific test type."""
        return [mod for mod, types in self.module_coverage.items() 
                if test_type in types]
    
    def calculate_shannon_entropy(self) -> float:
        """Calculate Shannon entropy of test types distribution."""
        total = sum(self.test_registry.values())
        if total == 0:
            return 0.0
        entropy = 0.0
        for score in self.test_registry.values():
            if score > 0:
                p = score / total
                entropy -= p * (p and (p ** 0.5))  # Simplified log approximation
        return entropy
    
    def calculate_coverage_breadth(self) -> float:
        """Calculate coverage breadth as ratio of covered modules."""
        if not self.module_coverage:
            return 0.0
        total_modules = len(self.module_coverage)
        covered = sum(1 for types in self.module_coverage.values() if types)
        return covered / total_modules if total_modules > 0 else 0.0
    
    def calculate_novelty_score(self) -> float:
        """Calculate novelty score based on unique test types."""
        unique_types = len([t for t, s in self.test_registry.items() if s > 0])
        total_types = len(self.test_registry)
        return unique_types / total_types if total_types > 0 else 0.0
    
    def get_diversity_metrics(self) -> Dict[str, float]:
        """Get all diversity metrics."""
        return {
            "shannon_entropy": self.calculate_shannon_entropy(),
            "coverage_breadth": self.calculate_coverage_breadth(),
            "novelty_score": self.calculate_novelty_score()
        }
    
    def generate_uncovered_templates(self) -> List[str]:
        """Generate test templates for uncovered scenarios."""
        templates = []
        uncovered_types = [t for t, s in self.test_registry.items() if s == 0]
        for test_type in uncovered_types:
            template = [
                "import pytest",
                "",
                f"def test_{test_type}_scenario():",
                f"    \"\"\"Test template for {test_type} scenario.\"\"\"",
                "    # TODO: Implement test logic",
                "    assert True",
                "",
            ]
            templates.append("\n".join(template))
        return templates
    
    def add_environmental_pressure(self, pressure_type: str, params: Dict) -> None:
        """Add an environmental pressure constraint."""
        pressure = {
            "type": pressure_type,
            "params": params,
            "active": True
        }
        self.environmental_pressures.append(pressure)
    
    def get_active_pressures(self) -> List[Dict]:
        """Get all active environmental pressures."""
        return [p for p in self.environmental_pressures if p.get("active", False)]
    
    def apply_performance_constraint(self, max_time: float = 1.0) -> Dict:
        """Apply a performance constraint pressure."""
        pressure = {
            "type": "performance",
            "params": {"max_execution_time": max_time},
            "active": True
        }
        self.environmental_pressures.append(pressure)
        return pressure
    
    def apply_resource_limit(self, memory_mb: int = 256, cpu_cores: int = 1) -> Dict:
        """Apply a resource limit pressure."""
        pressure = {
            "type": "resource_limit",
            "params": {"max_memory_mb": memory_mb, "max_cpu_cores": cpu_cores},
            "active": True
        }
        self.environmental_pressures.append(pressure)
        return pressure
    
    def apply_adversarial_input(self, input_type: str = "random") -> Dict:
        """Apply an adversarial input pressure."""
        pressure = {
            "type": "adversarial",
            "params": {"input_type": input_type},
            "active": True
        }
        self.environmental_pressures.append(pressure)
        return pressure
    
    def generate_environmental_pressure(self) -> Dict:
        """Generate a comprehensive environmental pressure test that combines timeout, memory, input size, and concurrency constraints.
        
        Returns:
            Dict containing the generated pressure test details with keys:
                - type: str, the pressure type identifier
                - params: Dict with timeout, memory_limit, input_size_bounds, and concurrency
                - test_code: str, the generated test function code
                - active: bool, whether this pressure is active
        """
        timestamp = hashlib.md5(str(random.random()).encode()).hexdigest()[:8]
        
        # Generate random parameters for the pressure test
        timeout = round(random.uniform(0.1, 5.0), 2)  # Timeout in seconds
        memory_limit = random.randint(64, 1024)  # Memory limit in MB
        input_size_min = random.randint(1, 100)
        input_size_max = random.randint(input_size_min + 10, input_size_min + 1000)
        concurrency_level = random.randint(1, 10)
        
        # Create the pressure test code
        test_code = [
            "import pytest",
            "import time",
            "import sys",
            "import threading",
            "from concurrent.futures import ThreadPoolExecutor, TimeoutError",
            "",
            "",
            f"def test_environmental_pressure_{timestamp}():",
            f"    \"\"\"Environmental pressure test: timeout={timeout}s, memory={memory_limit}MB, input_size=[{input_size_min},{input_size_max}], concurrency={concurrency_level}.\"\"\"",
            "    # Timeout constraint",
            f"    timeout_duration = {timeout}",
            "    start_time = time.time()",
            "    ",
            "    # Memory limit constraint (approximate check)",
            f"    memory_limit_bytes = {memory_limit} * 1024 * 1024",
            "    ",
            "    # Input size bounds",
            f"    input_size_min = {input_size_min}",
            f"    input_size_max = {input_size_max}",
            "    test_input_size = random.randint(input_size_min, input_size_max)",
            "    ",
            "    # Concurrency requirement",
            f"    concurrency_level = {concurrency_level}",
            "    ",
            "    def worker(worker_id):",
            "        \"\"\"Simulate work under pressure constraints.\"\"\"",
            "        # Check timeout",
            "        if time.time() - start_time > timeout_duration:",
            "            raise TimeoutError(f\"Worker {worker_id} timed out\")",
            "        ",
            "        # Simulate memory usage (approximate)",
            "        data = [i for i in range(test_input_size)]",
            "        ",
            "        # Simulate processing",
            "        result = sum(data) / len(data) if data else 0",
            "        return result",
            "    ",
            "    # Execute with concurrency",
            "    with ThreadPoolExecutor(max_workers=concurrency_level) as executor:",
            "        futures = [executor.submit(worker, i) for i in range(concurrency_level)]",
            "        ",
            "        # Wait for results with timeout",
            "        results = []",
            "        for future in futures:",
            "            try:",
            "                result = future.result(timeout=timeout_duration)",
            "                results.append(result)",
            "            except TimeoutError:",
            "                pytest.fail(f\"Worker timed out after {timeout_duration}s\")",
            "            except Exception as e:",
            "                pytest.fail(f\"Worker failed: {str(e)}\")",
            "    ",
            "    # Verify results",
            "    assert len(results) == concurrency_level, f\"Expected {concurrency_level} results, got {len(results)}\"",
            "    assert all(isinstance(r, (int, float)) for r in results), \"All results should be numeric\"",
            "    ",
            "    # Verify execution time",
            "    elapsed = time.time() - start_time",
            "    assert elapsed <= timeout_duration * 2, f\"Test took too long: {elapsed}s\"",
            "",
        ]
        
        pressure = {
            "type": "environmental_pressure",
            "params": {
                "timeout": timeout,
                "memory_limit_mb": memory_limit,
                "input_size_bounds": {"min": input_size_min, "max": input_size_max},
                "concurrency": concurrency_level
            },
            "test_code": "\n".join(test_code),
            "active": True
        }
        
        self.environmental_pressures.append(pressure)
        return pressure
    
    def mutate_test_suite(self, project_root: str, test_dir: str = "tests") -> List[str]:
        """Scan test directory, create new synthetic test, mutate existing test, return modified files."""
        mutator = TestSuiteMutator(test_dir)
        modified_files = []
        
        # Generate new test
        new_file = mutator.generate_new_test()
        if new_file:
            modified_files.append(new_file)
        
        # Mutate existing test
        mutated_file = mutator.mutate_existing_test()
        if mutated_file:
            modified_files.append(mutated_file)
        
        # Generate templates for uncovered scenarios
        templates = self.generate_uncovered_templates()
        for i, template in enumerate(templates):
            template_file = os.path.join(test_dir, f"test_template_{i}.py")
            with open(template_file, "w") as f:
                f.write(template)
            modified_files.append(template_file)
        
        # Generate environmental pressure test
        pressure = self.generate_environmental_pressure()
        pressure_file = os.path.join(test_dir, f"test_environmental_pressure_{hashlib.md5(str(random.random()).encode()).hexdigest()[:8]}.py")
        with open(pressure_file, "w") as f:
            f.write(pressure["test_code"])
        modified_files.append(pressure_file)
        
        return modified_files
    
    def mutate_fitness_landscape(self, project_root: str, test_dir: str = "tests") -> Dict:
        """Introduce new test files into the test suite."""
        result = {
            "action": "mutate",
            "success": False,
            "details": ""
        }
        
        test_path = os.path.join(project_root, test_dir)
        if not os.path.isdir(test_path):
            result["details"] = f"Test directory not found: {test_path}"
            return result
        
        mutator = TestSuiteMutator(test_path)
        
        # Generate new test
        try:
            new_file = mutator.generate_new_test()
            result["success"] = True
            result["details"] = f"Created new test file: {new_file}"
            
            # Add diversity metrics
            result["diversity_metrics"] = self.get_diversity_metrics()
            
            # Add environmental pressures
            if random.random() < 0.3:
                pressure = self.apply_performance_constraint(max_time=random.uniform(0.5, 2.0))
                result["pressure_applied"] = pressure
                
            # Generate environmental pressure test
            env_pressure = self.generate_environmental_pressure()
            result["environmental_pressure"] = env_pressure
                
        except Exception as e:
            result["details"] = f"Failed to create test file: {str(e)}"
        
        return result


# Global instance for backward compatibility
_evolver = TestSuiteEvolver()


def mutate_fitness_landscape(project_root: str, test_dir: str = "tests") -> Dict:
    """Hook called by the evolution orchestrator."""
    return _evolver.mutate_fitness_landscape(project_root, test_dir)


def run_ecology_cycle(project_root: str, test_dir: str = "tests") -> Dict:
    """Runs one full ecology engine cycle."""
    return mutate_fitness_landscape(project_root, test_dir)