"""
Ecology Engine: Mutates the fitness landscape by injecting new test cases and benchmarks.
Integrates with the evolution orchestrator via a mutate_fitness_landscape hook.
"""

import os
import random
from typing import Dict, List, Optional, Set


class TestSuiteEvolver:
    """Maintains a registry of test types and their diversity score."""
    
    def __init__(self):
        self.test_registry: Dict[str, float] = {
            "unit": 0.0,
            "integration": 0.0,
            "stress": 0.0,
            "adversarial": 0.0,
            "edge_case": 0.0
        }
        self.module_coverage: Dict[str, Set[str]] = {}
    
    def register_test_type(self, test_type: str, diversity_score: float = 0.5) -> None:
        """Register a new test type with its diversity score."""
        self.test_registry[test_type] = diversity_score
    
    def update_diversity_score(self, test_type: str, score: float) -> None:
        """Update the diversity score for a test type."""
        if test_type in self.test_registry:
            self.test_registry[test_type] = score
    
    def get_diversity_score(self, test_type: str) -> float:
        """Get the diversity score for a test type."""
        return self.test_registry.get(test_type, 0.0)
    
    def track_module_test(self, module_name: str, test_type: str) -> None:
        """Track which modules are tested by which test types."""
        if module_name not in self.module_coverage:
            self.module_coverage[module_name] = set()
        self.module_coverage[module_name].add(test_type)
    
    def get_modules_for_test_type(self, test_type: str) -> List[str]:
        """Get all modules tested by a specific test type."""
        return [mod for mod, types in self.module_coverage.items() 
                if test_type in types]
    
    def generate_new_test_type(self) -> str:
        """Create novel test scenarios."""
        test_types = [
            "stress_test",
            "adversarial_test",
            "integration_test",
            "performance_test",
            "security_test",
            "compatibility_test",
            "regression_test",
            "smoke_test"
        ]
        new_type = random.choice(test_types)
        self.register_test_type(new_type, random.uniform(0.1, 1.0))
        return new_type
    
    def mutate_fitness_landscape(self, project_root: str, test_dir: str = "tests") -> Dict:
        """Introduce new test files into the test suite."""
        result = {
            "action": "mutate",
            "success": False,
            "details": ""
        }
        
        test_path = os.path.join(project_root, test_dir)
        if not os.path.isdir(test_path):
            result["details"] = "Test directory not found: {}".format(test_path)
            return result
        
        # Generate a new test type
        new_test_type = self.generate_new_test_type()
        
        # Create a new test file
        file_name = "test_{}_{}.py".format(new_test_type, random.randint(1000, 9999))
        file_path = os.path.join(test_path, file_name)
        
        # Build test file content
        lines = []
        lines.append("import pytest")
        lines.append("")
        lines.append("")
        lines.append("# {} generated by Ecology Engine".format(new_test_type.replace("_", " ").title()))
        lines.append("")
        lines.append("")
        lines.append("def test_{}_scenario_1():".format(new_test_type))
        lines.append("    \"\"\"First scenario for {}.\"\"\"".format(new_test_type))
        lines.append("    assert True")
        lines.append("")
        lines.append("")
        lines.append("def test_{}_scenario_2():".format(new_test_type))
        lines.append("    \"\"\"Second scenario for {}.\"\"\"".format(new_test_type))
        lines.append("    assert True")
        lines.append("")
        
        try:
            with open(file_path, "w") as f:
                f.write("\n".join(lines))
            
            # Track the new test type
            self.track_module_test(new_test_type, new_test_type)
            
            result["success"] = True
            result["details"] = "Created new test file: {} with type: {}".format(
                file_path, new_test_type
            )
        except IOError as e:
            result["details"] = "Failed to create test file: {}".format(str(e))
        
        return result


# Global instance for backward compatibility
_evolver = TestSuiteEvolver()


def mutate_fitness_landscape(project_root: str, test_dir: str = "tests") -> Dict:
    """Hook called by the evolution orchestrator."""
    return _evolver.mutate_fitness_landscape(project_root, test_dir)


def run_ecology_cycle(project_root: str, test_dir: str = "tests") -> Dict:
    """Runs one full ecology engine cycle."""
    return mutate_fitness_landscape(project_root, test_dir)