from typing import List, Dict, Any, Optional
from enum import Enum

class GoalType(Enum):
    REPAIR = "repair"
    NEW_CAPABILITY = "new_capability"
    TEST_HARNESS = "test_harness"
    META_OPTIMIZATION = "meta_optimization"
    ECOLOGICAL_PRESSURE = "ecological_pressure"

class Goal:
    """Represents a goal with its type, dependencies, and priority."""
    
    def __init__(self, goal_id: str, goal_type: GoalType, dependencies: List[str] = None, 
                 priority: int = 0, metadata: Dict[str, Any] = None):
        self.goal_id = goal_id
        self.goal_type = goal_type
        self.dependencies = dependencies or []
        self.priority = priority
        self.metadata = metadata or {}
        self.completed = False

    def __repr__(self):
        return f"Goal({self.goal_id}, {self.goal_type.value}, priority={self.priority})"


class GoalSelector:
    """
    Goal selector with integration test awareness and consolidation priority.
    
    When test_mode is True, repair goals generated by the test harness are 
    prioritized over new capability goals, and must be processed in dependency order.
    
    When consolidation_priority is True and a high-confidence consolidation plan is detected,
    consolidation goals are elevated above new capability goals.
    
    Ecological pressure goals have the highest priority and are processed before any other goal type.
    """
    
    def __init__(self, test_mode: bool = False, consolidation_priority: bool = False):
        self.test_mode = test_mode
        self.consolidation_priority = consolidation_priority
        self.goals: List[Goal] = []
        self.completed_goals: List[Goal] = []
        self.pending_repair_goals: List[Goal] = []
        self.pending_new_goals: List[Goal] = []
        self.pending_consolidation_goals: List[Goal] = []
        self.pending_meta_optimization_goals: List[Goal] = []
        self.pending_ecological_pressure_goals: List[Goal] = []
        self.stagnation_counter = 0
        self.last_fitness_improvement = True

    def add_goal(self, goal: Goal) -> None:
        """Add a goal to the selector."""
        if self.test_mode and goal.goal_type == GoalType.REPAIR:
            self.pending_repair_goals.append(goal)
        elif goal.goal_type == GoalType.NEW_CAPABILITY:
            self.pending_new_goals.append(goal)
        elif goal.goal_type == GoalType.META_OPTIMIZATION:
            self.pending_meta_optimization_goals.append(goal)
        elif goal.goal_type == GoalType.ECOLOGICAL_PRESSURE:
            self.pending_ecological_pressure_goals.append(goal)
        else:
            self.goals.append(goal)

    def add_consolidation_goal(self, goal: Goal) -> None:
        """Add a consolidation goal to the selector."""
        self.pending_consolidation_goals.append(goal)

    def _get_repair_goals_in_dependency_order(self) -> List[Goal]:
        """
        Return repair goals sorted by dependency order.
        Uses topological sort to ensure dependencies are processed first.
        """
        if not self.pending_repair_goals:
            return []

        # Build dependency graph
        goal_map = {g.goal_id: g for g in self.pending_repair_goals}
        visited = set()
        sorted_goals = []

        def dfs(goal_id: str) -> None:
            if goal_id in visited:
                return
            visited.add(goal_id)
            goal = goal_map.get(goal_id)
            if goal:
                for dep_id in goal.dependencies:
                    if dep_id in goal_map:
                        dfs(dep_id)
                sorted_goals.append(goal)

        for goal in self.pending_repair_goals:
            dfs(goal.goal_id)

        return sorted_goals

    def _get_consolidation_goals_in_dependency_order(self) -> List[Goal]:
        """
        Return consolidation goals sorted by dependency order.
        Uses topological sort to ensure dependencies are processed first.
        """
        if not self.pending_consolidation_goals:
            return []

        # Build dependency graph
        goal_map = {g.goal_id: g for g in self.pending_consolidation_goals}
        visited = set()
        sorted_goals = []

        def dfs(goal_id: str) -> None:
            if goal_id in visited:
                return
            visited.add(goal_id)
            goal = goal_map.get(goal_id)
            if goal:
                for dep_id in goal.dependencies:
                    if dep_id in goal_map:
                        dfs(dep_id)
                sorted_goals.append(goal)

        for goal in self.pending_consolidation_goals:
            dfs(goal.goal_id)

        return sorted_goals

    def _get_meta_optimization_goals_in_dependency_order(self) -> List[Goal]:
        """
        Return meta-optimization goals sorted by dependency order.
        Uses topological sort to ensure dependencies are processed first.
        """
        if not self.pending_meta_optimization_goals:
            return []

        # Build dependency graph
        goal_map = {g.goal_id: g for g in self.pending_meta_optimization_goals}
        visited = set()
        sorted_goals = []

        def dfs(goal_id: str) -> None:
            if goal_id in visited:
                return
            visited.add(goal_id)
            goal = goal_map.get(goal_id)
            if goal:
                for dep_id in goal.dependencies:
                    if dep_id in goal_map:
                        dfs(dep_id)
                sorted_goals.append(goal)

        for goal in self.pending_meta_optimization_goals:
            dfs(goal.goal_id)

        return sorted_goals

    def _get_ecological_pressure_goals_in_dependency_order(self) -> List[Goal]:
        """
        Return ecological pressure goals sorted by dependency order.
        Uses topological sort to ensure dependencies are processed first.
        """
        if not self.pending_ecological_pressure_goals:
            return []

        # Build dependency graph
        goal_map = {g.goal_id: g for g in self.pending_ecological_pressure_goals}
        visited = set()
        sorted_goals = []

        def dfs(goal_id: str) -> None:
            if goal_id in visited:
                return
            visited.add(goal_id)
            goal = goal_map.get(goal_id)
            if goal:
                for dep_id in goal.dependencies:
                    if dep_id in goal_map:
                        dfs(dep_id)
                sorted_goals.append(goal)

        for goal in self.pending_ecological_pressure_goals:
            dfs(goal.goal_id)

        return sorted_goals

    def check_stagnation(self, fitness_improved: bool) -> Optional[Goal]:
        """
        Check for stagnation in meta-parameter evolution.
        
        If no fitness improvement for 5 consecutive cycles, generate a meta-optimization
        goal to explore parameter space more aggressively (e.g., temporarily increase mutation rate).
        
        Args:
            fitness_improved: Whether fitness improved in the current cycle
            
        Returns:
            A meta-optimization goal if stagnation is detected, None otherwise
        """
        if fitness_improved:
            self.stagnation_counter = 0
            self.last_fitness_improvement = True
        else:
            self.stagnation_counter += 1
            self.last_fitness_improvement = False

        if self.stagnation_counter >= 5:
            # Reset counter to avoid generating multiple goals for the same stagnation period
            self.stagnation_counter = 0
            
            # Create a meta-optimization goal to explore parameter space more aggressively
            meta_goal = Goal(
                goal_id=f"meta_opt_stagnation_{len(self.completed_goals) + len(self.pending_meta_optimization_goals)}",
                goal_type=GoalType.META_OPTIMIZATION,
                priority=100,  # High priority to ensure it gets processed
                metadata={
                    "reason": "stagnation_detected",
                    "stagnation_cycles": 5,
                    "action": "increase_mutation_rate",
                    "mutation_rate": 0.3,
                    "description": "No fitness improvement for 5 cycles. Temporarily increasing mutation rate to 0.3 to explore parameter space more aggressively."
                }
            )
            self.add_goal(meta_goal)
            return meta_goal
        
        return None

    def select_next_goal(self, system_state: Optional[Any] = None) -> Optional[Goal]:
        """
        Select the next goal to process based on current mode and feasibility score.
        
        Ecological pressure goals have the highest priority and are processed first.
        In test_mode, repair goals are prioritized and processed in dependency order.
        When consolidation_priority is True and consolidation goals exist, they are 
        prioritized over new capability goals.
        Meta-optimization goals are processed after repair and consolidation but before new capabilities.
        In normal mode, goals are selected by priority.
        
        Only accepts goals whose feasibility score exceeds the system state's goal_acceptance_threshold.
        """
        # Helper function to check if a goal meets the acceptance threshold
        def is_goal_acceptable(goal: Goal) -> bool:
            if system_state is None:
                return True
            threshold = getattr(system_state, 'goal_acceptance_threshold', 0.0)
            feasibility = goal.metadata.get('feasibility_score', 0.0)
            return feasibility > threshold

        # Process ecological pressure goals first (highest priority)
        if self.pending_ecological_pressure_goals:
            eco_goals = self._get_ecological_pressure_goals_in_dependency_order()
            if eco_goals:
                for goal in eco_goals:
                    if all(dep in [g.goal_id for g in self.completed_goals] 
                           for dep in goal.dependencies) and is_goal_acceptable(goal):
                        self.pending_ecological_pressure_goals.remove(goal)
                        return goal
                return None

        if self.test_mode:
            # Process repair goals first, in dependency order
            repair_goals = self._get_repair_goals_in_dependency_order()
            if repair_goals:
                # Find the first repair goal whose dependencies are all completed and is acceptable
                for goal in repair_goals:
                    if all(dep in [g.goal_id for g in self.completed_goals] 
                           for dep in goal.dependencies) and is_goal_acceptable(goal):
                        self.pending_repair_goals.remove(goal)
                        return goal
                
                # If no repair goal has all dependencies met or is acceptable, return None
                # (wait for dependencies to be completed or threshold to be met)
                return None

        # Check consolidation priority if enabled
        if self.consolidation_priority and self.pending_consolidation_goals:
            consolidation_goals = self._get_consolidation_goals_in_dependency_order()
            if consolidation_goals:
                # Find the first consolidation goal whose dependencies are all completed and is acceptable
                for goal in consolidation_goals:
                    if all(dep in [g.goal_id for g in self.completed_goals] 
                           for dep in goal.dependencies) and is_goal_acceptable(goal):
                        self.pending_consolidation_goals.remove(goal)
                        return goal
                
                # If no consolidation goal has all dependencies met or is acceptable, return None
                # (wait for dependencies to be completed or threshold to be met)
                return None

        # Process meta-optimization goals (after repair and consolidation, before new capabilities)
        if self.pending_meta_optimization_goals:
            meta_goals = self._get_meta_optimization_goals_in_dependency_order()
            if meta_goals:
                for goal in meta_goals:
                    if all(dep in [g.goal_id for g in self.completed_goals] 
                           for dep in goal.dependencies) and is_goal_acceptable(goal):
                        self.pending_meta_optimization_goals.remove(goal)
                        return goal
                return None

        # Fall back to normal priority-based selection
        all_goals = self.pending_new_goals + self.goals
        if not all_goals:
            return None

        # Filter goals by acceptance threshold and select the highest priority acceptable goal
        acceptable_goals = [g for g in all_goals if is_goal_acceptable(g)]
        if not acceptable_goals:
            return None

        # Select the highest priority acceptable goal
        acceptable_goals.sort(key=lambda g: g.priority, reverse=True)
        selected = acceptable_goals[0]
        
        if selected in self.pending_new_goals:
            self.pending_new_goals.remove(selected)
        else:
            self.goals.remove(selected)
        
        return selected

    def complete_goal(self, goal: Goal) -> None:
        """Mark a goal as completed."""
        goal.completed = True
        self.completed_goals.append(goal)

    def get_pending_goals(self) -> List[Goal]:
        """Get all pending goals."""
        return (self.goals + self.pending_repair_goals + self.pending_new_goals + 
                self.pending_consolidation_goals + self.pending_meta_optimization_goals +
                self.pending_ecological_pressure_goals)

    def has_pending_repair_goals(self) -> bool:
        """Check if there are any pending repair goals."""
        return len(self.pending_repair_goals) > 0

    def has_pending_consolidation_goals(self) -> bool:
        """Check if there are any pending consolidation goals."""
        return len(self.pending_consolidation_goals) > 0

    def has_pending_meta_optimization_goals(self) -> bool:
        """Check if there are any pending meta-optimization goals."""
        return len(self.pending_meta_optimization_goals) > 0

    def has_pending_ecological_pressure_goals(self) -> bool:
        """Check if there are any pending ecological pressure goals."""
        return len(self.pending_ecological_pressure_goals) > 0

    def clear(self) -> None:
        """Clear all goals and reset state."""
        self.goals.clear()
        self.completed_goals.clear()
        self.pending_repair_goals.clear()
        self.pending_new_goals.clear()
        self.pending_consolidation_goals.clear()
        self.pending_meta_optimization_goals.clear()
        self.pending_ecological_pressure_goals.clear()
        self.stagnation_counter = 0
        self.last_fitness_improvement = True


def create_goal_selector(test_mode: bool = False, consolidation_priority: bool = False) -> GoalSelector:
    """
    Factory function to create a GoalSelector with the specified mode.
    
    Args:
        test_mode: When True, enables integration test awareness mode
        consolidation_priority: When True, elevates consolidation goals above new capability goals
        
    Returns:
        Configured GoalSelector instance
    """
    return GoalSelector(test_mode=test_mode, consolidation_priority=consolidation_priority)