from typing import List, Dict, Any, Optional
from enum import Enum

class GoalType(Enum):
    REPAIR = "repair"
    NEW_CAPABILITY = "new_capability"
    TEST_HARNESS = "test_harness"

class Goal:
    """Represents a goal with its type, dependencies, and priority."""
    
    def __init__(self, goal_id: str, goal_type: GoalType, dependencies: List[str] = None, 
                 priority: int = 0, metadata: Dict[str, Any] = None):
        self.goal_id = goal_id
        self.goal_type = goal_type
        self.dependencies = dependencies or []
        self.priority = priority
        self.metadata = metadata or {}
        self.completed = False

    def __repr__(self):
        return f"Goal({self.goal_id}, {self.goal_type.value}, priority={self.priority})"


class GoalSelector:
    """
    Goal selector with integration test awareness and consolidation priority.
    
    When test_mode is True, repair goals generated by the test harness are 
    prioritized over new capability goals, and must be processed in dependency order.
    
    When consolidation_priority is True and a high-confidence consolidation plan is detected,
    consolidation goals are elevated above new capability goals.
    """
    
    def __init__(self, test_mode: bool = False, consolidation_priority: bool = False):
        self.test_mode = test_mode
        self.consolidation_priority = consolidation_priority
        self.goals: List[Goal] = []
        self.completed_goals: List[Goal] = []
        self.pending_repair_goals: List[Goal] = []
        self.pending_new_goals: List[Goal] = []
        self.pending_consolidation_goals: List[Goal] = []

    def add_goal(self, goal: Goal) -> None:
        """Add a goal to the selector."""
        if self.test_mode and goal.goal_type == GoalType.REPAIR:
            self.pending_repair_goals.append(goal)
        elif goal.goal_type == GoalType.NEW_CAPABILITY:
            self.pending_new_goals.append(goal)
        else:
            self.goals.append(goal)

    def add_consolidation_goal(self, goal: Goal) -> None:
        """Add a consolidation goal to the selector."""
        self.pending_consolidation_goals.append(goal)

    def _get_repair_goals_in_dependency_order(self) -> List[Goal]:
        """
        Return repair goals sorted by dependency order.
        Uses topological sort to ensure dependencies are processed first.
        """
        if not self.pending_repair_goals:
            return []

        # Build dependency graph
        goal_map = {g.goal_id: g for g in self.pending_repair_goals}
        visited = set()
        sorted_goals = []

        def dfs(goal_id: str) -> None:
            if goal_id in visited:
                return
            visited.add(goal_id)
            goal = goal_map.get(goal_id)
            if goal:
                for dep_id in goal.dependencies:
                    if dep_id in goal_map:
                        dfs(dep_id)
                sorted_goals.append(goal)

        for goal in self.pending_repair_goals:
            dfs(goal.goal_id)

        return sorted_goals

    def _get_consolidation_goals_in_dependency_order(self) -> List[Goal]:
        """
        Return consolidation goals sorted by dependency order.
        Uses topological sort to ensure dependencies are processed first.
        """
        if not self.pending_consolidation_goals:
            return []

        # Build dependency graph
        goal_map = {g.goal_id: g for g in self.pending_consolidation_goals}
        visited = set()
        sorted_goals = []

        def dfs(goal_id: str) -> None:
            if goal_id in visited:
                return
            visited.add(goal_id)
            goal = goal_map.get(goal_id)
            if goal:
                for dep_id in goal.dependencies:
                    if dep_id in goal_map:
                        dfs(dep_id)
                sorted_goals.append(goal)

        for goal in self.pending_consolidation_goals:
            dfs(goal.goal_id)

        return sorted_goals

    def select_next_goal(self) -> Optional[Goal]:
        """
        Select the next goal to process based on current mode.
        
        In test_mode, repair goals are prioritized and processed in dependency order.
        When consolidation_priority is True and consolidation goals exist, they are 
        prioritized over new capability goals.
        In normal mode, goals are selected by priority.
        """
        if self.test_mode:
            # Process repair goals first, in dependency order
            repair_goals = self._get_repair_goals_in_dependency_order()
            if repair_goals:
                # Find the first repair goal whose dependencies are all completed
                for goal in repair_goals:
                    if all(dep in [g.goal_id for g in self.completed_goals] 
                           for dep in goal.dependencies):
                        self.pending_repair_goals.remove(goal)
                        return goal
                
                # If no repair goal has all dependencies met, return None
                # (wait for dependencies to be completed)
                return None

        # Check consolidation priority if enabled
        if self.consolidation_priority and self.pending_consolidation_goals:
            consolidation_goals = self._get_consolidation_goals_in_dependency_order()
            if consolidation_goals:
                # Find the first consolidation goal whose dependencies are all completed
                for goal in consolidation_goals:
                    if all(dep in [g.goal_id for g in self.completed_goals] 
                           for dep in goal.dependencies):
                        self.pending_consolidation_goals.remove(goal)
                        return goal
                
                # If no consolidation goal has all dependencies met, return None
                # (wait for dependencies to be completed)
                return None

        # Fall back to normal priority-based selection
        all_goals = self.pending_new_goals + self.goals
        if not all_goals:
            return None

        # Select the highest priority goal
        all_goals.sort(key=lambda g: g.priority, reverse=True)
        selected = all_goals[0]
        
        if selected in self.pending_new_goals:
            self.pending_new_goals.remove(selected)
        else:
            self.goals.remove(selected)
        
        return selected

    def complete_goal(self, goal: Goal) -> None:
        """Mark a goal as completed."""
        goal.completed = True
        self.completed_goals.append(goal)

    def get_pending_goals(self) -> List[Goal]:
        """Get all pending goals."""
        return self.goals + self.pending_repair_goals + self.pending_new_goals + self.pending_consolidation_goals

    def has_pending_repair_goals(self) -> bool:
        """Check if there are any pending repair goals."""
        return len(self.pending_repair_goals) > 0

    def has_pending_consolidation_goals(self) -> bool:
        """Check if there are any pending consolidation goals."""
        return len(self.pending_consolidation_goals) > 0

    def clear(self) -> None:
        """Clear all goals and reset state."""
        self.goals.clear()
        self.completed_goals.clear()
        self.pending_repair_goals.clear()
        self.pending_new_goals.clear()
        self.pending_consolidation_goals.clear()


def create_goal_selector(test_mode: bool = False, consolidation_priority: bool = False) -> GoalSelector:
    """
    Factory function to create a GoalSelector with the specified mode.
    
    Args:
        test_mode: When True, enables integration test awareness mode
        consolidation_priority: When True, elevates consolidation goals above new capability goals
        
    Returns:
        Configured GoalSelector instance
    """
    return GoalSelector(test_mode=test_mode, consolidation_priority=consolidation_priority)