"""core/nash_bootstrap.py

Minimal bootstrap module that:
(1) Scans the core/ directory for all .py files
(2) Creates a dependency graph
(3) Generates __init__.py with correct imports
(4) Creates stub modules for any missing dependencies referenced by nash_detector_and_forcer
"""

import ast
import os
import sys
from pathlib import Path
from typing import Dict, List, Set, Tuple

# Known dependencies referenced by nash_detector_and_forcer
KNOWN_DEPENDENCIES = {
    'nash_detector_and_forcer',
    'coordinated_mutation_engine',
    'ecology_engine',
    'nash_equilibrium',
    'nash_bootstrap',
}


def get_core_dir() -> Path:
    """Get the path to the core/ directory."""
    # Assume this file is in core/
    return Path(__file__).parent.resolve()


def scan_py_files(core_dir: Path) -> List[Path]:
    """Scan core/ directory for all .py files (excluding __init__.py)."""
    py_files = []
    for f in core_dir.glob('*.py'):
        if f.name != '__init__.py' and f.name != '__pycache__':
            py_files.append(f)
    return py_files


def extract_imports(filepath: Path) -> Set[str]:
    """Extract all module-level imports from a Python file using AST."""
    imports = set()
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            tree = ast.parse(f.read(), filename=str(filepath))
        
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    # Get the top-level module name
                    top_level = alias.name.split('.')[0]
                    imports.add(top_level)
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    top_level = node.module.split('.')[0]
                    imports.add(top_level)
    except (SyntaxError, UnicodeDecodeError) as e:
        print(f"Warning: Could not parse {filepath}: {e}")
    
    return imports


def build_dependency_graph(py_files: List[Path]) -> Dict[str, Set[str]]:
    """Build a dependency graph mapping module names to their dependencies."""
    graph = {}
    for f in py_files:
        module_name = f.stem
        imports = extract_imports(f)
        # Filter to only include core modules and known dependencies
        core_modules = {imp for imp in imports if imp in KNOWN_DEPENDENCIES or 
                       any(f.parent.name == 'core' for f in py_files if f.stem == imp)}
        graph[module_name] = core_modules
    return graph


def topological_sort(graph: Dict[str, Set[str]]) -> List[str]:
    """Perform topological sort on the dependency graph."""
    # Build reverse dependency map
    reverse_deps = {node: set() for node in graph}
    for node, deps in graph.items():
        for dep in deps:
            if dep in reverse_deps:
                reverse_deps[dep].add(node)
    
    # Kahn's algorithm
    in_degree = {node: len(deps) for node, deps in graph.items()}
    queue = [node for node, degree in in_degree.items() if degree == 0]
    sorted_nodes = []
    
    while queue:
        node = queue.pop(0)
        sorted_nodes.append(node)
        for dependent in reverse_deps.get(node, set()):
            in_degree[dependent] -= 1
            if in_degree[dependent] == 0:
                queue.append(dependent)
    
    # If there are cycles, add remaining nodes
    remaining = set(graph.keys()) - set(sorted_nodes)
    if remaining:
        print(f"Warning: Cycle detected in dependencies: {remaining}")
        sorted_nodes.extend(remaining)
    
    return sorted_nodes


def generate_init_content(sorted_modules: List[str], graph: Dict[str, Set[str]]) -> str:
    """Generate the content for __init__.py with correct imports."""
    lines = [
        '"""Core package auto-generated by nash_bootstrap."""',
        '',
        '# Auto-generated imports in dependency order',
        '',
    ]
    
    for module in sorted_modules:
        lines.append(f'from core.{module} import *  # noqa: F401, F403')
    
    lines.extend([
        '',
        '# Explicit exports',
        '__all__ = [',
    ])
    
    for module in sorted_modules:
        lines.append(f'    "{module}",')
    
    lines.append(']')
    lines.append('')
    
    return '\n'.join(lines)


def create_stub_module(module_name: str, core_dir: Path) -> Path:
    """Create a stub module for a missing dependency."""
    stub_path = core_dir / f'{module_name}.py'
    
    stub_content = f'''"""
{module_name}.py

Auto-generated stub module for missing dependency.
Created by nash_bootstrap to satisfy import requirements.
"""

# Stub classes and functions for nash_detector_and_forcer compatibility


class NashEquilibrium:
    """Stub Nash equilibrium detector."""
    
    def __init__(self):
        self.equilibrium_found = False
        self.equilibrium_state = None
    
    def detect(self, state: dict) -> bool:
        """Stub detection method."""
        return self.equilibrium_found
    
    def force(self, state: dict) -> dict:
        """Stub forcing method."""
        return state


class MutationEngine:
    """Stub coordinated mutation engine."""
    
    def __init__(self):
        self.mutations = []
    
    def apply_mutation(self, code: str, context: dict) -> str:
        """Stub mutation application."""
        return code


class EcologyEngine:
    """Stub ecology engine."""
    
    def __init__(self):
        self.pressure = 0.0
    
    def evolve(self, code: str) -> str:
        """Stub evolution method."""
        return code


def detect_nash(state: dict) -> bool:
    """Stub function for Nash equilibrium detection."""
    return False


def force_nash(state: dict) -> dict:
    """Stub function for Nash equilibrium forcing."""
    return state


def apply_mutation(code: str, context: dict = None) -> str:
    """Stub function for mutation application."""
    return code


def evolve_code(code: str) -> str:
    """Stub function for code evolution."""
    return code


# Export common names
__all__ = [
    'NashEquilibrium',
    'MutationEngine',
    'EcologyEngine',
    'detect_nash',
    'force_nash',
    'apply_mutation',
    'evolve_code',
]
'''
    
    with open(stub_path, 'w', encoding='utf-8') as f:
        f.write(stub_content)
    
    print(f"Created stub module: {stub_path}")
    return stub_path


def check_missing_dependencies(graph: Dict[str, Set[str]], core_dir: Path) -> Set[str]:
    """Check for missing dependencies and create stubs if needed."""
    existing_modules = {f.stem for f in core_dir.glob('*.py') if f.stem != '__init__'}
    all_deps = set()
    for deps in graph.values():
        all_deps.update(deps)
    
    missing = all_deps - existing_modules - {'__init__'}
    
    for dep in missing:
        if dep in KNOWN_DEPENDENCIES:
            create_stub_module(dep, core_dir)
    
    return missing


def bootstrap() -> bool:
    """Main bootstrap function. Returns True if successful."""
    try:
        core_dir = get_core_dir()
        print(f"Bootstrapping core/ directory: {core_dir}")
        
        # Scan for Python files
        py_files = scan_py_files(core_dir)
        print(f"Found {len(py_files)} Python files")
        
        # Build dependency graph
        graph = build_dependency_graph(py_files)
        print(f"Built dependency graph with {len(graph)} modules")
        
        # Check for missing dependencies
        missing = check_missing_dependencies(graph, core_dir)
        if missing:
            print(f"Created stub modules for: {', '.join(missing)}")
        
        # Re-scan after creating stubs
        py_files = scan_py_files(core_dir)
        graph = build_dependency_graph(py_files)
        
        # Topological sort
        sorted_modules = topological_sort(graph)
        print(f"Module load order: {', '.join(sorted_modules)}")
        
        # Generate __init__.py
        init_content = generate_init_content(sorted_modules, graph)
        init_path = core_dir / '__init__.py'
        
        with open(init_path, 'w', encoding='utf-8') as f:
            f.write(init_content)
        
        print(f"Generated {init_path}")
        return True
        
    except Exception as e:
        print(f"Bootstrap failed: {e}")
        return False


def main():
    """Entry point for running bootstrap directly."""
    success = bootstrap()
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()